# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190313_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
    ]
