# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190313_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Prefer not to say')], max_length=1),
        ),
    ]
