# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Prefer not to say')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro - $9.99/mo')], max_length=30),
        ),
    ]
