# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-14 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190314_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='uploaded_at',
        ),
    ]
