# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='video_url',
            new_name='url',
        ),
    ]
