# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0005_auto_20190227_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='not_found'),
        ),
    ]
