# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0007_tv_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_channel',
            old_name='currently_streaming',
            new_name='program',
        ),
    ]
