# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0008_auto_20190227_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_channel',
            name='url',
            field=models.URLField(default='not_found'),
        ),
    ]
