# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0009_tv_channel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=8)),
                ('release_date', models.DateField()),
                ('url', models.URLField()),
                ('slug', models.SlugField(default='not_found')),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='release_date',
        ),
    ]
