# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0011_podcast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Songs',
        ),
    ]
