# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0012_auto_20190318_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
