# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0013_auto_20190318_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='default', upload_to='media/music_thumbnails'),
            preserve_default=False,
        ),
    ]
