# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0014_song_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
