# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-30 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0015_auto_20190326_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='videofile',
            field=models.FileField(default='not found', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(upload_to='music_thumbnails'),
        ),
    ]
