# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0017_auto_20190329_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='not found', upload_to='movie_thumbnails'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, default='not found', upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, default='not found', upload_to='videos/'),
        ),
    ]
