# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0018_auto_20190418_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='not found', max_length=100),
        ),
    ]
