# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0023_auto_20190505_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='year_of_release',
        ),
    ]
