# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0024_auto_20190505_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('comedy', 'Comedy'), ('kids', 'Kids'), ('action', 'Action'), ('teen', 'Teen'), ('drama', 'Drama')], default=None, max_length=29),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(choices=[('indie', 'Indie'), ('professional', 'Professional')], default='Professional', max_length=10),
        ),
    ]
