# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0025_auto_20190516_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre1',
            field=models.CharField(choices=[('-------', '-------'), ('comedy', 'Comedy'), ('kids', 'Kids'), ('action', 'Action'), ('teen', 'Teen'), ('drama', 'Drama')], default=None, max_length=100, verbose_name='Main genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre2',
            field=models.CharField(choices=[('-------', '-------'), ('comedy', 'Comedy'), ('kids', 'Kids'), ('action', 'Action'), ('teen', 'Teen'), ('drama', 'Drama')], default=None, max_length=100, verbose_name='Sub-genre 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre3',
            field=models.CharField(choices=[('-------', '-------'), ('comedy', 'Comedy'), ('kids', 'Kids'), ('action', 'Action'), ('teen', 'Teen'), ('drama', 'Drama')], default=None, max_length=100, verbose_name='Sub-genre 2'),
        ),
    ]
