# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0027_auto_20190516_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre1',
            field=models.CharField(choices=[('-------', '-------'), ('Comedy', 'Comedy'), ('Kids', 'Kids'), ('Action', 'Action'), ('Teen', 'Teen'), ('Drama', 'Drama')], default=None, max_length=100, verbose_name='Main genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre2',
            field=models.CharField(choices=[('-------', '-------'), ('Comedy', 'Comedy'), ('Kids', 'Kids'), ('Action', 'Action'), ('Teen', 'Teen'), ('Drama', 'Drama')], default=None, max_length=100, verbose_name='Sub-genre 1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre3',
            field=models.CharField(choices=[('-------', '-------'), ('Comedy', 'Comedy'), ('Kids', 'Kids'), ('Action', 'Action'), ('Teen', 'Teen'), ('Drama', 'Drama')], default=None, max_length=100, verbose_name='Sub-genre 2'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.CharField(choices=[('Indie', 'Indie'), ('Professional', 'Professional')], default=None, max_length=100),
        ),
    ]
