# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0028_auto_20190516_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
