# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 15:31
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0029_remove_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre2',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre3',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('-------', '-------'), ('Comedy', 'Comedy'), ('Kids', 'Kids'), ('Action', 'Action'), ('Teen', 'Teen'), ('Drama', 'Drama')], default=None, max_length=37),
            preserve_default=False,
        ),
    ]
