# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0030_auto_20190520_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='company',
            new_name='publication',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, default='not found', upload_to='podcast_audio/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='podcast_thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
