# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_platform', '0033_auto_20190529_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='users',
        ),
        migrations.AddField(
            model_name='favorite',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='streaming_platform.Movie'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='podcast',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='streaming_platform.Podcast'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='streaming_platform.Song'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tv_channel',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='streaming_platform.TV_channel'),
        ),
    ]
