# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streaming_platform', '0034_auto_20190529_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='song',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='tv_channel',
        ),
        migrations.AddField(
            model_name='favorite',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movie_set', to='streaming_platform.Movie'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='podcasts',
            field=models.ManyToManyField(blank=True, related_name='podcast_set', to='streaming_platform.Podcast'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='song_set', to='streaming_platform.Song'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='tv_channels',
            field=models.ManyToManyField(blank=True, related_name='tv_channel_set', to='streaming_platform.TV_channel'),
        ),
    ]
